### ISSUE TITLE
Add list of recent bins

### ISSUE THREAD

**Issue by groteworld** [groteworld/request-tab#3]
Haven't looked into this at all, but you should be able to get your recent bins, based on cookie. This would help prevent the over creation of bins, as well as support getting to a older bin.

**Comment by isacssouza** [comment]
Local storage (sync?) could be used to maintain a list of the bins created and a list with the last ~5 bins could be displayed when the popup is shown.

**Comment by groteworld** [comment]
Yeah, we have access to localstorage in the extension.

On the requestbin page this disclaimer is below...

> Limits: This bin will keep the last 20 requests made to it and remain available for 48 hours after it was created. However, data might be cleared at any time, so treat bins as highly ephemeral.

So localstorage could save the bin id as the key and the create datetime as the value. Then when RequestTab is opened it checks for expiration (48 hours old) and shows the bins not expired. Deleting bins that are expired.
